
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

# Whitelist
http:
  
  # traefik subnet
  trusted_proxies:
    - 48.84.0.0/16 #update to match 'traefik' subnet

  use_x_forwarded_for: true
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io

# Side Panel NAV
panel_iframe:
  node_red:
    title: "Node Red"
    url: "http://node-red.home"
    icon: mdi:resistor-nodes
    require_admin: true
  zigbee2mqtt:
    title: "Zigbee2MQTT"
    url: "http://zigbee2mqtt.home"
    icon: mdi:zigbee
    require_admin: true

# DB
recorder:
  purge_keep_days: 14

# MQTT Broker
mqtt:
  discovery: true
  broker: mosquitto #mosquitto container hostname / service name
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
